/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.childcare.model.DAO;

import com.childcare.entity.Account;
import com.childcare.entity.Child;
import com.childcare.entity.Device;
import com.childcare.entity.Family;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.io.Serializable;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.annotation.Resource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.PreparedStatementCreator;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;

/**
 *
 * @author New User
 */
public class DAOChild {
      @Resource 
    private JdbcTemplate jdbcTemplate;
      
         protected class ChildMapper implements RowMapper,Serializable{  
            /**
             * 
             * @param arg0 the ResultSet to map (pre-initialized for the current row)
             * @param arg1 the number of the current row
             * @return
             * @throws SQLException 
             */
        @Override  
        public Object mapRow(ResultSet arg0, int arg1) throws SQLException {  
            // TODO Auto-generated method stub  
            Child child = new Child();
            child.setAge(arg0.getInt("Age"));  
            child.setCid(arg0.getInt("CID"));
            child.setName(arg0.getString("Name"));
            child.setImage(arg0.getString("Image"));
            child.setDeviceID(new Device(arg0.getString("DeviceID")));
            child.setFid(new Family(arg0.getInt("FID")));
            return child;  
        }  
    }
         
    public void editImage(int cid,String image)
    {
        String sql = "UPDATE `GSV_DB`.`Child`\n" +
                     " SET\n" +
                     " `Image` = '"+image+"' \n" +
                     " WHERE `CID` = "+cid+";";
        this.jdbcTemplate.execute(sql);
    }
         
    /**
     * create a new child record
     * @param child
     * @return CID of created record
     */
    public int create(Child child)
    {
        String did = "null";
        if (child.getDeviceID()!=null)
            did = "'"+child.getDeviceID().getDeviceID()+"'";
        String sql = "INSERT INTO `GSV_DB`.`Child`\n" +
                     "("+
                     "`FID`,\n" +
                     "`DeviceID`,\n" +
                     "`Name`,\n" +
                     "`Image`,\n" +
                     "`Age`) \n" +
                     "VALUES \n" +
                     "("+
                     child.getFid().getFid()+",\n" +
                     did+",\n" +
                     "'"+child.getName()+"',\n" +
                     "'"+child.getImage()+"',\n" +
                     child.getAge()+");";
          KeyHolder keyHolder = new GeneratedKeyHolder();             
            int updatecount/*number of effected rows*/ = this.jdbcTemplate.update(new PreparedStatementCreator() {  
            @Override  
            public PreparedStatement createPreparedStatement(Connection connection) throws SQLException {  
            PreparedStatement ps = (PreparedStatement) connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);  
            return ps;  }},keyHolder);
            int id = keyHolder.getKey().intValue(); 
            return id;
            //http://fancyboy2050.iteye.com/blog/1455559
            //在JDBC 3.0规范中，当新增记录时，允许将数据库自动产生的主键值绑定到Statement或PreparedStatement中
            //当autoGeneratedKeys参数设置为Statement.RETURN_GENERATED_KEYS值时即可绑定数据库产生的主键值，设置为Statement.NO_GENERATED_KEYS时，不绑定主键值。
    }
    
    public void update(Child child)
    {
                String did = "null";
        if (child.getDeviceID()!=null)
            did = "'"+child.getDeviceID().getDeviceID()+"'";
        String sql = "UPDATE `GSV_DB`.`Child`\n" +
                     " SET\n" +
                     " `FID` = "+child.getFid().getFid()+",\n" +
                     " `DeviceID` = "+did+",\n" +
                     " `Name` = '"+child.getName()+"',\n" +
                     " `Age` = "+child.getAge()+"\n" +
                     " WHERE `CID` = "+child.getCid()+";";
        this.jdbcTemplate.execute(sql);
    }
    
    public Child findByCID(int cid)
    {
        String sql = "select * FROM `GSV_DB`.`Child` WHERE `CID` = "+cid+";";
        return (Child)this.jdbcTemplate.queryForObject(sql,new ChildMapper());
    }
    
    public Child findByDevice(String deviceID)
    {  
        String sql = "select * FROM `GSV_DB`.`Child` WHERE `DeviceID` = '"+deviceID+"';";
        List<Child> list = this.jdbcTemplate.query(sql,new ChildMapper());
        if (list.isEmpty())
            return null;
        else return list.get(0);
    }
    
    public List<Child> findByFID(int fid)
    {
        String sql = "SELECT * FROM `GSV_DB`.`Child` WHERE `Child`.`FID` = "+fid+"  ;";
        List<Child> list = this.jdbcTemplate.query(sql,new ChildMapper());
        return list;
    }
    
    public List<Child> findByUID(long uid)
    {
        String sql = "Select * from `GSV_DB`.`Child` where `Child`.`FID` in (select `FID` from `Account_Family` where `UID` = "+uid+")";
        List<Child> list = this.jdbcTemplate.query(sql,new ChildMapper());
        return list;
    }
    
    public void delete(int cid)
    {
        String sql = "DELETE FROM `GSV_DB`.`Child` WHERE `CID` = "+cid+";";
        this.jdbcTemplate.execute(sql);
    }
}
